version: '2'
services:
  service: # Main
    build: .
    environment:
      NODE_ENV: 'development'
    volumes:
      - ./:/home/node/app
      # This will prevent node_modules from being mounted
      - /home/node/app/node_modules/
    ports:
      - 80:8000
    networks:
      - default
